services:
    shoppygo.hook.action.employee.form.builder.modifier:
        class: ShoppyGo\MarketplaceBundle\HookListener\EmployeeActionFormBuilderModifierListener
        arguments:
            - '@shoppygo.provider.seller.choices'
            - '@shoppygo.core'
            - '@shoppygo.marketplace.repository.seller_repository'
        calls:
            - [ setHooks,[ [ 'actionEmployeeFormBuilderModifier' ] ] ]
            - [ setSellerSelectWidget,['@shoppygo.widget.seller.select']]
        tags:
            - { name: 'shoppygo.hook', alias: 'actionemployeeformbuildermodifier' }

    shoppygo.hook.action.after.create.employee.form.handler:
        class: ShoppyGo\MarketplaceBundle\HookListener\EmployeeHookAfterCreateListener
        arguments:
            - '@shoppygo.provider.seller.choices'
            - '@shoppygo.core'
            - '@shoppygo.marketplace.repository.seller_repository'
            - '@prestashop.core.form.identifiable_object.builder.employee_form_builder'
        calls:
            - [ setHooks,[ [ 'actionAfterCreateEmployeeFormHandler' ] ] ]
        tags:
            - { name: 'shoppygo.hook', alias: 'actionaftercreateemployeeformhandler' }

    shoppygo.hook.action.after.update.employee.form.handler:
        class: ShoppyGo\MarketplaceBundle\HookListener\EmployeeHookAfterUpdateListener
        arguments:
            - '@shoppygo.provider.seller.choices'
            - '@shoppygo.core'
            - '@shoppygo.marketplace.repository.seller_repository'
            - '@prestashop.core.form.identifiable_object.builder.employee_form_builder'
        calls:
            - [ setHooks,[ [ 'actionAfterUpdateEmployeeFormHandler' ] ] ]
        tags:
            - { name: 'shoppygo.hook', alias: 'actionafterupdateemployeeformhandler' }

    shoppygo.hook.action.employee.grid.definition.modifier:
        class: ShoppyGo\MarketplaceBundle\HookListener\EmployeeHookActionGridDefinitionModifierListener
        arguments:
            - '@shoppygo.provider.seller.choices'
            - '@shoppygo.core'
            - '@shoppygo.marketplace.repository.seller_repository'
            - '@translator.default'
        calls:
            - [ setHooks,[ [ 'actionEmployeeGridDefinitionModifier' ] ] ]
        tags:
            - { name: 'shoppygo.hook', alias: 'actionemployeegriddefinitionmodifier' }

    shoppygo.hook.action.employee.grid.query.builder.modifier:
        class: ShoppyGo\MarketplaceBundle\HookListener\EmployeeHookActionGridQueryBuilderModifierListener
        arguments:
            - '@shoppygo.provider.seller.choices'
            - '@shoppygo.core'
            - '@shoppygo.marketplace.repository.seller_repository'
            - '@translator.default'
        calls:
            - [ setHooks,[ [ 'actionEmployeeGridQueryBuilderModifier' ] ] ]
        tags:
            - { name: 'shoppygo.hook', alias: 'actionemployeegridquerybuildermodifier' }

    shoppygo.hook.action.products.results.fields.modifier:
        class: ShoppyGo\MarketplaceBundle\HookListener\ProductsActionAdminListingResultsModifierListener
        arguments:
            - '@shoppygo.core'
            - '@shoppygo.marketplace.repository.seller_repository'
            - '@translator.default'
        calls:
            - [ setHooks,[ [ 'actionAdminProductsListingFieldsModifier' ] ] ]
        tags:
            - { name: 'shoppygo.hook', alias: 'actionadminproductslistingfieldsmodifier' }

