services:
    shoppygo.widget.seller.select:
        class: ShoppyGo\MarketplaceBundle\Form\Widget\SellerSelectWidget
        arguments:
            - '@shoppygo.provider.seller.choices'
    shoppygo.widget.seller.switch:
        class: ShoppyGo\MarketplaceBundle\Form\Widget\SellerSwitchWidget
